title: Running CESM in Four Steps & Analyzing Output
author: Jiang Zhu
logo: images/paleoCAMPLogo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/jiang-zhu/paleocamp2025
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

myst:
  enable_extensions:
    - attrs_image
# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

myst_enable_extensions:
  - colon_fence
  - deflist
  - html_admonition
  - html_image
